from __future__ import annotations
from collections.abc import Mapping
from typing import Protocol
from app.models.observability import CounterMetric, DurationMetric, ObservabilityEvent

class EventSink(Protocol):
    def emit(self, event: ObservabilityEvent) -> ObservabilityEvent: ...
    def list_events(self, *, correlation_id: str | None = None, event_type: str | None = None, limit: int = 100) -> list[ObservabilityEvent]: ...

class MetricsSink(Protocol):
    def increment_counter(self, name: str, *, value: int = 1, labels: Mapping[str, str] | None = None) -> CounterMetric: ...
    def observe_duration(self, name: str, duration_ms: float, *, labels: Mapping[str, str] | None = None) -> DurationMetric: ...
    def counters(self) -> list[CounterMetric]: ...
    def durations(self) -> list[DurationMetric]: ...